// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommunesController from "./communes_controller"
application.register("communes", CommunesController)

import AirflowController from "./airflow_controller"
application.register("airflow", AirflowController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
