
meta_name: "Geocool"
meta_title: "GeoCool - Unique configurateur de puits climatique"
meta_description: "Geocool vous permet de dimensionner des systèmes de puits canadien selon les caractéristiques de votre projet de construction ou rénovation."
meta_image: "meta-image.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
